worker_processes auto;
daemon off;

error_log stderr warn;

events {
    # For deployment in Kubernetes we should always "use epoll" (most efficient). Optionally you can disable it for local testing.
    use epoll;
    worker_connections 1024;
    multi_accept on;
}


http {
    charset utf-8;
    # Disable access logs, we use k8s ingress to monitor access
    access_log off;

    # Configuration inspired by https://stackoverflow.com/questions/29354142/
    map_hash_bucket_size 256; # see http://nginx.org/en/docs/hash.html
    map $request_uri $external_uri {
        default 0;
        include /etc/nginx/redirects.map;
    }
    map $request_uri $allow {
        default 0;
        include /etc/nginx/allow.map;
    }

    server {
        listen 80 default_server;

        # Used by Kubernetes health checks
        location /nginx-health {
            default_type application/json;
            return 200 '{"status":"healthy"}';
        }

        if ($external_uri != 0) {
            return 302 $external_uri;
        }

        # If there's no match we'll try to find the page in the wayback machine
        if ($allow = 0) {
            return 302 https://wayback.archive-it.org/12090/*/https://pro.europeana.eu$request_uri;
        }

        return 200 'Request handled by Pro';
    }

}
