apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-redirect-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pro-redirect
          imagePullPolicy: Never